name: 'Setup Xcode version'
author: 'Maxim Lobanov'
description: 'Set up your GitHub Actions workflow with a specific version of Xcode'
inputs:
  xcode-version:
    description: 'Version of Xcode to use'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'code'
  color: 'blue'
